### ISSUE TITLE
Where is "Server Build"?

### ISSUE THREAD

**Issue by kvibert** [SoftwareGuy/NodeListServer-Example#1]
Where is "Server Build", I can't find it.

**Comment by SoftwareGuy** [comment]
**Inside Unity Editor:**

File Menu -> Build Settings... -> Select Windows/Mac/Linux desktop target and check "Server Build" box. Then Build/Build and Run.

Note that this is only present on newer 2018.3+ versions of Unity. Anything older will not have said option.

Refer to attached screenshot.
![image](https://user-images.githubusercontent.com/1762115/87411204-b660ef00-c60a-11ea-9da2-c6d4b44a0c44.png)

**Comment by kvibert** [comment]
Thanks!

**Comment by SoftwareGuy** [comment]
No problems, you're welcome.
