### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by Archadin** [SoftwareGuy/NodeListServer-Example#10]
I couldnt find the <b><i>"NodeListServerNetMan.cs"</i></b> file anywhere in the project. Can you tell me where i can find it?

![Screenshot 2022-03-02 104435](https://user-images.githubusercontent.com/65004554/156317190-d9315406-dbbd-4200-adac-d2bf6b02a746.png)

**Comment by SoftwareGuy** [comment]
I got rid of Mirror from the example project as now this basically just demonstrates a Server Browser list but it seems that people want to use this as a project base.

Give me a bit and I'll re-import Mirror and set things up again...

**Comment by Archadin** [comment]
Thanks a lot. i am actually trying to understand the script itself rather than using it as a project base but i couldnt get it to work after adding mirror network manager and a transport to the <b><i>Logic</i></b> gamobject. also in the readme there was this;

> The main logic you want to take a look at is the NodeListServerNetMan.cs file. That is pretty much a barebones Network Manager with NodeListServer Adapter calls added where appropriate. See the Example scene's objects in its Hierarchy. If you're using custom code, just add the Node List Server Adapter component somewhere, and then you can call it's public functions where needed.

explanation so i assumed i needed <b><i>"NodeListServerNetMan.cs"</i></b> file.

**Comment by Archadin** [comment]
If you dont mind me asking some more questions while i am at it. I wanted to ask a couple more questions.

Do i need to do anything other that creating a server build with this project ?

As i understand the NodeListServer is used for Adding/Removing servers to a directory which itself is another server(?) and listing existing servers for clients. So can i use this(after modifying it) with dedicated servers in playfab. Can i somehow get the list of dedicated servers in the playfab and show them to the clients for them to click and connect to ?

btw what i mean up there is that if i can accomplish all these without making a heavy customization to the original code.

Sorry for the long question and all the gibberish.

**Comment by SoftwareGuy** [comment]
> If you dont mind me asking some more questions while i am at it. I wanted to ask a couple more questions.
> 
> Do i need to do anything other that creating a server build with this project ?

This project is best used as a reference point, when I put Mirror back in place I will include a slightly modified version of Pong that usually ships with Mirror. You would just build that scene into a player and it'll automatically connect and register up.

> As i understand the NodeListServer is used for Adding/Removing servers to a directory which itself is another server(?) and listing existing servers for clients. So can i use this(after modifying it) with dedicated servers in playfab. Can i somehow get the list of dedicated servers in the playfab and show them to the clients for them to click and connect to ?
> 
> btw what i mean up there is that if i can accomplish all these without making a heavy customization to the original code.

Yeah, you could customize this code to a PlayFab server list displaying setup.

> Sorry for the long question and all the gibberish.

All good mate, if you didn't ask questions then you wouldn't get answers 😉

**Comment by Archadin** [comment]
Thank you for the help. I will open a new ticket or ask from Mirror discord channel if i get stuck again.
