### ISSUE TITLE
An error occurs when start the server.

### ISSUE THREAD

**Issue by kvibert** [SoftwareGuy/NodeListServer-Example#2]
There's an error when start the server, please see the log:

Initialize engine version: 2018.4.1f1 (b7c424a951c0)
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Completed reload, in  0.072 seconds
UnloadTime: 0.434400 ms
TelepathyTransport initialized!

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Server: Start port=7777

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Server: listening port=7777

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 4 Unused Serialized files (Serialized files now loaded: 0)
Refreshing the server list...

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Working...

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

UnloadTime: 30.965200 ms
Multiple NetworkManagers detected in the scene. Only one NetworkManager can exist at a time. The duplicate NetworkManager will be destroyed.

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

TelepathyTransport initialized!

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 38 unused Assets to reduce memory usage. Loaded Objects now: 569.
Total: 1.801700 ms (FindLiveObjects: 0.120300 ms CreateObjectMapping: 0.011500 ms MarkObjects: 1.643700 ms  DeleteObjects: 0.026000 ms)

NodeLS: Mission failed. We'll get them next time.
An error occurred while registering the server. One or more required fields, like the server GUID, name and port might be missing. You will need to fix this and call RegisterServer again to retry.

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Cannot connect to destination host

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

NodeLS: But it's not over yet. Get ready for the next round: retrying as an update as specified.

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

NodeLS: Mission failed. We'll get them next time.
An error occurred while updating the server information. The communication key or the server GUID might be wrong, or some other information is bogus. Or it could be you are experiencing connection problems.

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

NodeLS: But it's not over yet, get ready for the next round. Retrying update as registration.

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

**Comment by SoftwareGuy** [comment]
Please check the following:

- Make sure you're running the NodeListServer instance. This is not included with the example project, you'll need to follow the steps on the [NodeLS repository](https://github.com/SoftwareGuy/NodeListServer). 

- Set *Listserver Connect Url* to the IP address of your server that you're running NodeLS on. For example, if you have it hosted on your own server, you'd set it as `http://127.0.0.1:8889`. Omit a trailing slash.
- Set *Listserver Auth Key* only to another value if you've modified your NodeLS configuration file.
- Server Guid should be left alone. That's autopopulated, or you can set your own if you want. *Best to leave it alone.*

![image](https://user-images.githubusercontent.com/1762115/87497571-21f19d80-c699-11ea-8d91-dca3619168e8.png)
